[phases.setup]
nixPkgs = ["glibc", "gcc", "python311", "spacy", "bash"]
cmds = ["python -m spacy download en_core_web_sm"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmds = ["gunicorn -w 4 -b 0.0.0.0:8080 app:app"]
